trigger:
  branches:
    include:
      - master
      - develop
      - azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildNumber: $(Build.BuildNumber)
  sourceBranch: $(Build.SourceBranchName)
  artifactDir: $(Build.ArtifactStagingDirectory)

steps:
  - script: 'echo $(buildNumber)'
  - script: 'echo $(sourceBranch)'
  - script: 'echo $(artifactDir)'